version: '3'
services:
  redis:
    image: redis:latest
  mailhog:
    image: "mailhog/mailhog:latest"
  catapulte:
    build: .
    ports:
      - "3200:3200"
    environment:
      - "mailer_host=mailhog"
      - "mailer_port=1025"
      - "redis_url=redis://redis"
